TOOLS =[
    {
        'type':'function',
        'function':{
            'name':'add',
            'description':'used to perform addition between 2 parameters',
            'parameters':{
                'type':'object',
                'properties':{
                    'x':{'type':'number'},
                    'y':{'type':'number'}
                },
                'required':['x','y']
            }
        }
    },
    {
        'type':'function',
        'function':{
            'name':'sub',
            'description':'used to perform substraction between parameters',
            'parameters':{
                'type':'object',
                'properties':{
                    'x':{'type':'number'},
                    'y':{'type':'number'}
                },
                'required':['x','y']
            }
        }
    },
    {
        'type':'function',
        'function':{
            'name':'mul',
            'description':'used to perform multiplication between 2 parameters',
            'parameters':{
                'type':'object',
                'properties':{
                    'x':{'type':'number'},
                    'y':{'type':'number'}
                },
                'required':['x','y']
            }
        }
    },
    {
        'type':'function',
        'function':{
            'name':'div',
            'description':'used to perform division between 2 parameters',
            'parameters':{
                'type':'object',
                'properties':{
                    'x':{'type':'number'},
                    'y':{'type':'number'}
                },
                'required':['x','y']
            }
        }
    },
    {
        'type':'function',
        'function':{
            'name':'pow',
            'description':'used to perform power between 2 parameters',
            'parameters':{
                'type':'object',
                'properties':{
                    'x':{'type':'number'},
                    'y':{'type':'number'}
                },
                'required':['x','y']
            }
        }
    },
    {
        'type':'function',
        'function':{
            'name':'mod',
            'description':'used to perform modulus operation on the passed parameter',
            'parameters':{
                'type':'object',
                'properties':{
                    'x':{'type':'number'}
                },
                'required':['x']
            }
        }
    },
    {
        'type':'function',
        'function':{
            'name':'sqrt',
            'description':'used to perform square root operation on the passed parameter',
            'parameters':{
                'type':'object',
                'properties':{
                    'x':{'type':'number'}
                },
                'required':['x']
            }
        }
    }
]